config_spine.txt
In accordance with [BIDS specs](https://github.com/bids-standard/bids-specification/blob/2c81be7c745721ecd14a8bafdd53b360da378424/src/04-modality-specific-files/01-magnetic-resonance-imaging-data.md#diffusion-imaging-data)
=> Fix dwi b0 name

processing/generate_figure.py
Fix issue when individual subject's data did not appear in graphs for some metrics. Reason was that these individual subject's data did not have set scaling.
Fixes #58
=> set scaling for individual subjects

processing/populate_derivatives.py
This PR introduces a util script to copy manual corrections placed in a flat directory, under the BIDS_DATA/derivatives/ folder as per BIDS convention.
Related to #105
=> New script to copy manual corrections under derivatives/

processing/process_data.sh
Currently, users have to put all manual seg and label under a flat directory, under a folder called with the flag `PATH_SEGMANUAL` upon calling `sct_run_batch`.  Issues are:
- does not follow BIDS convention
- need to manually package the manual corrections and upload them for each release
- more complicated UX and documentation
This PR introduces the following changes:
- manual corrections go inside the BIDS dataset, under a `derivatives/` folder
- `process_data.sh` is modified to look for the manual corrections there
Fixes #3
Remaining TODOs (after merging this PR):
- update documentation (related to https://github.com/spine-generic/spine-generic/pull/103)
- upload manual corrections under derivatives/: https://github.com/spine-generic/spine-generic/issues/105
=> Look for manual files under derivatives/

docs/conf.py, docs/documentation.rst
Built doc on this branch: https://spine-generic.readthedocs.io/en/jv-100-broken_relative_link_fix
Fix: #100
=> switch from relative to absolute links in documentation

processing/process_data.sh
Because propseg results are slightly different across OSs (for more details, see neuropoly/spinalcordtoolbox#2769), the bug in #110 could occur. 
This PR fixes the problem by:
- replacing propseg by get_centerline
Fixes #110
=> Ensures reproducible pipeline across OSs; various improvements

setup.py, spinegeneric/cli/package_for_correction.py
In case processing is ran on a remote cluster, it would be convenient to generate a package of the files that need correction, to conveniently copy them locally (instead of copying the ~20GB of processed files). 
The proposed script, name `package_for_correction.py`, and called via CLI with `sg_package_for_correction`:
- take as input the yml file that lists the files to correct
- copy them in a temp folder
- zip the package
Fixes #128
TODO in other PRs
- document this new function in https://github.com/spine-generic/spine-generic/pull/122 (to prevent conflicts)
=> New script to package data awaiting correction

spinegeneric/cli/manual_correction.py
This PR introduces the creation of a json sidecar file, along with each corrected segmentation or label. This json includes the expert rater name and date of the correction. The name is entered (used is prompted on the CLI) when running `sg_manual_correction`.
Example of created json:
````json
{
"Author": "Julien Cohen-Adad",
"Date": "2020-07-22 12:04:47"
}
````
Fixes #143
=> Create json sidecar

docs/analysis_pipeline.rst, spinegeneric/cli/manual_correction.py, spinegeneric/utils.py
In this PR, we introduce the generation of a QC report of manual corrections, which can be uploaded alongside a new release of the spine-generic dataset.  Specific changes include:
- QC report for segmentations and label
- QC report generated locally
- QC report archived as zip file for convenient upload alongside data release on github
- Updated documentation on RTD
Fixes #145
=> Generate QC report for manual corrections

process_data.sh
In this example from `sub-ubc02`, where motion between odd and even scans created the following "zigzag" patterns:
The current registration parameter is causing problem, as it uses `algo=slicereg` (highly regularized along I-S axis). 
The proposed PR switches to `algo=centermass`.
Comparison in this qc report: [qc.zip](https://github.com/spine-generic/spine-generic/files/4997848/qc.zip)
Related to https://github.com/spine-generic/data-multi-subject/issues/9#issuecomment-665530406
Fixes #153
=> Changed slicereg to centermass for DWI registration

spinegeneric/cli/package_for_correction.py
Redefined root and base directory for the zip creation.
How to test:
```
git checkout af/improve_sg_package_for_correction
pip install -e .
sg_package_for_correction -config PATH_TO_YML -path-in DATASET_DATA/
```
@jcohenadad if it's easier for you to test, I can upload an yml & small dummy dataset. 
Fixes https://github.com/spine-generic/spine-generic/issues/139
Example of an output:
```
(base) alfoi_admin@joplin:~$ sg_package_for_correction -config config.yml -path-in dummy_test/ 
-> /mnt/nvme/tmp/tmpaiyvf34q/sub-chiba750/anat/sub-chiba750_T1w_RPI_r.nii.gz
-> /mnt/nvme/tmp/tmpaiyvf34q/sub-chiba750/anat/sub-chiba750_T1w_RPI_r_seg.nii.gz
-> /mnt/nvme/tmp/tmpaiyvf34q/sub-chiba750/anat/sub-chiba750_T2w_RPI_r.nii.gz
-> /mnt/nvme/tmp/tmpaiyvf34q/sub-chiba750/anat/sub-chiba750_T2w_RPI_r_seg.nii. …
```
=> Improve sg_package_for_correction

spinegeneric/cli/manual_correction.py
When running sg_manual_correction, the function create a zip archive of the QC folder, the yml file that was used as input (-config) is included.
To test:
```
git checkout af/improve_sg_manual_correction
sg_manual_correction -config PATH_TO_config.yml -path-in PATH_TO_DATA -path-out PATH_TO_DATA_OUTPUT
```
Fixes https://github.com/spine-generic/spine-generic/issues/157
=> Improve sg_manual_correction

spinegeneric/cli/manual_correction.py, spinegeneric/utils.py
This PR introduces the following changes to `manual_correction`:
- Added a flag `-qc-only` in the CLI to skip correction, and only generate the QC report. Fixes #159
- Major refactoring to simplify the code and enable the functionality above
- If corrected file already exists, asks user if they want to overwrite it
- Fixes TypeError is key is empty in yml file. Fixes #151
=> Added flag -qc-only; Major refactoring to simplify code

spinegeneric/cli/generate_figure.py
This PR fixes two cosmetic issues in figures generated by `sg_generate_figure` script:
- fix superscript in MD and RD ylabel
- change a.u. unit for MTsat to [%]
Fixes #163
=> fix superscript for MD and RD ylabel and remove a.u. unit for MTsat

spinegeneric/cli/generate_figure.py
This PR includes the following improvements:
- Exclude outlier sites from cov_intra computation. Fixes #178
- Do not display COV_intra for single-subject case. Fixes #180
- Display red cross if site is excluded from statistics.
- Adjust figure size horizontally based on number of sites.
- Adjust ylim, improved dynamic (ylim[0] is no more 0)
- Refactoring to nest functions and simplify code.
TODO:
- change flag: `-indiv-subj` --> `-indiv-sub` and document
=> generate_figure: small improvements; code clarifications

process_data.sh
The flag -dseg was missing to be able to generate QC report for those registrations.
Fixes #187
=> Add QC output for MT0->T1w and MT1->T1w registrations

process_data.sh
There was a bug for fetching the TR and FlipAngle from the json metadata in the current version of `process_data`, producing wrong results. See e.g. https://github.com/spine-generic/data-multi-subject/issues/44#issuecomment-686759403.
There is now a feature in SCT' `sct_compute_mtsat`, where TR and FA are automatically retrieved if the json sidecar is present. More details in https://github.com/neuropoly/spinalcordtoolbox/pull/2875.
This PR removes the shell-based fetching of the BIDS metadata and uses SCT's new Python-based feature instead.
=> Removed shell-based fetching of BIDS metadata for MTsat

docs/data-acquisition.rst, spinegeneric/cli/params_checker.py
Fixes #189 
Output example for single-subject:
```
(base) alfoi@MacBook-Pro:data-single-subject % sg_params_checker -path-in .
/Users/alfoi/miniconda3/lib/python3.7/site-packages/bids/layout/models.py:102: FutureWarning: The 'extension' entity currently excludes the leading dot ('.'). As of version 0.14.0, it will include the leading dot. To suppress this warning and include the leading dot, use `bids.config.set_option('extension_initial_dot', True)`.
FutureWarning)
WARNING: Incorrect FlipAngle: sub-douglas_T2w.nii.gz; FA=120 instead of 180
WARNING: Incorrect RepetitionTime: sub-mgh_T2w.nii.gz; TR=2 instead of 1.5
WARNING: Incorrect FlipAngle: sub-tokyoSigna1_T2star.nii.gz; FA=20 instead of 30
WARNING: Incorrect FlipAngle: sub-tokyoSigna2_T2star.nii.gz; FA=20 instead of 30 …
```
=> Parameters checker now sets tolerance on the absolute (unsigned) difference

spinegeneric/cli/params_checker.py
Fixes #191 
Output example from single-subject:
```
(base) alfoi@MacBook-Pro:data-single-subject % sg_params_checker -path-in .
/Users/alfoi/miniconda3/lib/python3.7/site-packages/bids/layout/models.py:102: FutureWarning: The 'extension' entity currently excludes the leading dot ('.'). As of version 0.14.0, it will include the leading dot. To suppress this warning and include the leading dot, use `bids.config.set_option('extension_initial_dot', True)`.
FutureWarning)
WARNING: sub-douglas_T2w.nii.gz: Incorrect FlipAngle: FA=120 instead of 180
WARNING: sub-mgh_T2w.nii.gz: Incorrect RepetitionTime: TR=2 instead of 1.5
WARNING: sub-tokyoSigna1_T2star.nii.gz: Incorrect FlipAngle: FA=20 instead of 30
WARNING: sub-tokyoSigna2_T2star.nii.gz: Incorrect FlipAngle: FA=20 instead of 30
WARNING: …
```
=> Clarify output display for params checker

spinegeneric/cli/generate_figure.py
Fixes #193 by adding a vector of subject in the dataframe, enabling to check potential mismatch in `generate_figure_t1_t2`.
Also clarified code of `compute_regression()` by moving higher level stuff (dict, vendor info) to the caller.
Alternative approach to https://github.com/spine-generic/spine-generic/pull/199
=> Fix different x and y size in t1-t2 agreement figure

spinegeneric/cli/generate_figure.py
This PR automatizes text generation based on results.
The feature is activated with the flag `-output-text`, then the `main` calls a function `output_text()` which performs writing of results into `statistical_results.txt` file.
P-values are rounded to two decimals, if p<0.01 (e.g. 0.003), it is replace by str "<0.01".
The output `statistical_results.txt` looks like:
Fixes: https://github.com/spine-generic/spine-generic/issues/204
=> Automatize text generation based on results

spinegeneric/cli/generate_figure.py
In this PR, I changed order of metrics in `file_to_metric` dict to corresponds with spine-generic protocol and manuscript. Then, output statistical results are also ordered in this order.
Fixes: https://github.com/spine-generic/spine-generic/issues/210
=> Sort metrics results to match sequence order in the spine-generic protocol

spinegeneric/cli/generate_figure.py
Sites that should be excluded when computing the ANOVA are not excluded. This PR fixes it.
Fixes #203
=> Exclude sites from ANOVA

spinegeneric/cli/generate_figure.py
This PR brings few improvements for the formatting of statistics output:
- Skip intra-site ANOVAs and pvalues if single-subject
- Remove the blurb about the intra-site COV if it is equal to 0 (ie: single-subject case).
- Removed COVs acronym definition
- Remove existing output txt file
- Output formatted statistics into the same log_stats.txt file
Fixes #214
=> Cosmetic improvements with formatted output of statistics

spinegeneric/cli/generate_figure.py
Round intra-site COV to the first decimal instead of using int in -output-text outputs.
before this PR:
`The intra-site COVs were averaged for each vendor and found to be all under 8%.`
with this PR:
`The intra-site COVs were averaged for each vendor and found to be all under 7.8%.`
( Values themself in this particular case are: )
Fixes: https://github.com/spine-generic/spine-generic/issues/220
=> Round intra-site COV to first decimal for output statistics text.

process_data.sh
This PR fixes two inconsistencies in `process_data.sh` comments:
- remove info about `RESTORE` algorithm - https://github.com/spine-generic/spine-generic/issues/169
- remove duplication of information regarding position of labels - https://github.com/spine-generic/spine-generic/issues/223
Fixes: #169 Fixes #223
=> Fix inconsistencies in proces_data.sh comments

spinegeneric/cli/generate_figure.py
This PR adds computation of min, max and median age across subjects from `participants.tsv` file
These stats are computed across all subjects (i.e., no exclusion is used).
Stats are then saved in form of prepared sentence for manuscript into `log_stats.txt` file:
`..., age between 19.0 and 56.0 y.o., median age 28.0 y.o..`
~~Known disadvantage of proposed solution - participants file is read for every metric in `aggregate_per_site` function:~~
https://github.com/spine-generic/spine-generic/blob/de8b6c9df0e4a28ad418be7f990cf726cb7e6bfd/spinegeneric/cli/generate_figure.py#L234-L235
~~Then, age stats are also saved into `log_stats.txt` file for every metric separately. I could add some counter to save age only one time. Should I?~~
UPDATE: separate function was created …
=> Compute min, max and median age across subjects

spinegeneric/cli/generate_figure.py
I have tried sg_generate_figure with acdavis flag extension and the graph generator worked fine and exported all figures as shown in Sci Data paper, only extended about VIDA ucdavis scanner.
Magnetization transfer for ucdavis appears off, comapred to other Siemens results.
=> add ucdavis flag into spinegeneric/cli/generate_figure.py

.flake8, .github/workflows/lint.yml
It is easier (and more conventional) to maintain.
Also, make lint.yml treat all flake warnings as errors, not just syntax problems. Previously, the linter had been turned down so that only four errors were actually errors, and the rest got --exit-zero, presumably to triage problems, but the time I found it both had been entirely disabled. I separated linting to a separate Action which I made non-mandatory, achieving the same effect, so now I think we can shorten the script to just run the full linter in the conventional way.
And if we can get the lint back under control then we can make it mandatory again.
=> Move flake8 configuration into .flake8

spinegeneric/cli/params_checker.py
This PR has 3 parts:
- The first 16 commits are refactoring commits to make the script clearer and more concise. They clean up the code style of the script, while also adding documentation to make certain aspects (`BIDSLayout`, `BIDSLayoutIndexer`) easier to understand.
- The second to last commit, dc73e639e714ce4c64286b1b013d92386a797954, fixes #264.
- The last commit, 4adaeb7f09dfe5e66a2cb940a25ceccf1a4a88a4, adds some TODOs for discussion in this PR. 
Running the script on `data-multi-subject` results in 142 warnings:
<details>
```
WARNING: sub-amu01_T2w.nii.gz: Incorrect RepetitionTime: TR=2 instead of 1.5 +/- 0.1.
WARNING: sub-amu01_T2w.nii.gz: Incorrect FlipAngle: FA=180 instead of 120.
WARNING: sub-amu02_T2w.nii.gz: Incorrect RepetitionTime: TR=2 instead of 1.5 +/- 0.1.
WARNING: …
```
=> Clean up `sg_params_checker` so it can be run on `data-multi-subject` without crashing

docs/analysis-pipeline.rst, docs/data-acquisition.rst
Rename MTS suffix to be in line with https://github.com/spine-generic/data-multi-subject/pull/135
```
acq-MTon_MTS → flip-1_mt-on_MTS
acq-MToff_MTS → flip-1_mt-off_MTS
acq-T1w_MTS → flip-2_mt-off_MTS
```
=> Documentation - Rename MTS suffix

docs/conf.py, requirements.txt
The ReadTheDocs page has been failing to build for the past year:
https://readthedocs.org/projects/spine-generic/builds/
Looking at the logs, it looks like this is because of a missing dependency in `requirements.txt` for the ReadTheDocs theme. According to the theme documentation for the latest version (3.0.1), it looks like the theme needs to be pip installed, and activated as an extension, and they recommend pinning the version:
https://sphinx-rtd-theme.readthedocs.io/en/3.0.1/installing.html
=> Specify sphinx-rtd-theme as a dependency
