spine-generic/spine-generic

processing/process_data.sh

Didn't have time to test the whole script yet, not really elegant but should do the trick
Fixes #27

added automatic parsing of json for TR and FA

---

processing/generate_figure.py
requirements.txt

Added T1w and T2w CSA agreement figures
Fixes #51

T1w and T2w CSA agreement figures

---

docs/documentation.rst
processing/deface_spineGeneric_usingR.py
processing/qc_bids_deface.py
processing/regular_deface.r
processing/special_deface.r

Not sure if the formatting of the code block is correct. I tried the preview in VS code and it looks okay.

update doc for defacing using R

---

processing/generate_figure.py

Included changes:
- added dynamic axis scaling of individual subplots
- added bisection (diagonal) line
- grid moved to background
I also increased size of linear fit equation, it resulted in conflict with vendor label, so I moved vendor label to lower-right corner.
Fixes: https://github.com/sct-pipeline/spine-generic/issues/57

Scaling adjustment, bisection line added, grid moved to background

---

processing/qc_bids_deface.py

Now asking the user to input the path for output report.

update qc generation

---

docs/_static/css/custom.css
docs/conf.py

Fixes https://github.com/sct-pipeline/spine-generic/issues/53
Looks like this:

Fix max width

---

docs/documentation.rst

The used font wites letter l and number 1 in a very similar way. It was hard to read, e.g. sub-ucl01. I can appear as sub-uc101. It took me few minutes to recognize the letter l in the string.

changed ucl at ubc

---

processing/qc_bids_deface.py

Fix qc report script

---

processing/qc_bids_deface.py

Fixes https://github.com/sct-pipeline/spine-generic/issues/67
The results using the single subject dataset look like this:

Fix qc image dynamic

---

processing/process_data.sh

Check if file exists before copying

---

docs/conf.py

Caused RTD build. Fixes #131
➤ Built doc: https://spine-generic.readthedocs.io/en/jca-131-rtd-build/

Added spinegeneric in path for import

---

spinegeneric/cli/generate_figure.py

Excluded this subject from T2w CSA and DTI analyses due to reacquisition of T2w with repositioning.
Fixes #76
Related to https://github.com/spine-generic/data-multi-subject/issues/9#issuecomment-665971630

Exclude sub-mountSinai03 from some analyses

---

spinegeneric/cli/generate_figure.py

- Rename sapienza --> fslAchieva
- Add flag for fslPrisma
Fixes https://github.com/spine-generic/spine-generic/issues/165

Fix generate figure

---

spinegeneric/cli/generate_figure.py

I forgot to push my local changes before merging #185, so this PR fixes it.

Fix to #185: Changed location for output stats log file

---

spinegeneric/cli/generate_figure.py

add excluded sites into output txt file
before:
```
csa-SC_T2w.csv
====================================================
Subjects removed: ['sub-pavia04', 'sub-mountSinai03', 'sub-oxfordFmrib04']
```
now:
```
csa-SC_T2w.csv
====================================================
Subjects removed: ['sub-pavia04', 'sub-mountSinai03', 'sub-oxfordFmrib04']
Sites removed: ['beijingVerio']
```
Fixes: https://github.com/spine-generic/spine-generic/issues/216

List excluded sites into output txt file

---

docs/analysis-pipeline.rst
requirements.txt
spinegeneric/__init__.py
spinegeneric/cli/create_mosaic.py

Fixes https://github.com/spine-generic/spine-generic/issues/225
To try (on Compute Canada):
```
module load python/3.7
git checkout af/fix_create_mosaic
pip install -e .
sg_create_mosaic -i *T1w_RPI_r_flatten.nii.gz -ifolder ~/project/results_multi_20200907/data_processed/ -s _seg.nii.gz -p sag -col 20 -row 12 -o fig_mosaic_T1w.png
```

sg_create_mosaic: Fix issues with modules compatibility; various improvements

---

docs/data-acquisition.rst

Added section imaging protocol under data collection and organization
To test : https://spine-generic.readthedocs.io/en/af-im_protocol_section/data-acquisition.html#
Fixes https://github.com/spine-generic/spine-generic/issues/233

Create section "Imaging Protocol"

---

requirements.txt
spinegeneric/cli/check_data_consistency.py

Fixes https://github.com/spine-generic/spine-generic/issues/231
To test:
```
git checkout af/improve-ci-participants
sg_check_data_consistency -path-in ~/path_data-multi-subject
```
To test use dataset: https://github.com/spine-generic/data-multi-subject/pull/57 
Example output:
```
Checking the contents of participants.tsv
{row: 0, column: "height"}: "-" was not in the range [0, 250)
{row: 0, column: "weight"}: "-" was not in the range [0, 250)
{row: 1, column: "height"}: "-" was not in the range [0, 250)
{row: 1, column: "weight"}: "-" was not in the range [0, 250)
{row: 2, column: "height"}: "-" was not in the range [0, 250)
{row: 2, column: "weight"}: "-" was not in the range [0, 250)
{row: 3, column: "height"}: "-" was not in the range [0, 250)
{row: 3, column: "weight"}: "-" was not …
```

Implemented test for participants.tsv in CI

---

spinegeneric/cli/qc_bids_deface.py

Fixes https://github.com/spine-generic/spine-generic/issues/246

Fix sg_qc_bids_deface

---

process_data.sh

PR is related to the issue #254

Use dwi run-01 if multiple dwi runs exist

---

docs/analysis-pipeline.rst

This PR updates example commands in `analysis-pipeline.rst` file

edit tweak in docs/analysis-pipeline.rst file

---

process_data.sh

This PR adresses #274 and is related to the update of the spine generic data-multi-subject to be BIDS compilent : https://github.com/spine-generic/data-multi-subject/pull/159 
I ran the entire processing on the database of the [branch](https://github.com/spine-generic/data-multi-subject/pull/159) and the processing was completed for all subjects except 2: (sub-oxfordFmrib04 and sub-oxfordOhba02) they are in the exclude list for T2w.
Closes #271
Closes #274

Update naming convention in `process_data.sh`
